// web-app-v/src/components/ui/Button.tsx
import React from 'react';
import { Loader2 } from 'lucide-react';

export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: 'primary' | 'secondary' | 'ghost' | 'danger' | 'outline';
  size?: 'sm' | 'md' | 'lg';
  isLoading?: boolean;
  glow?: boolean;
  leftIcon?: React.ReactNode;
  rightIcon?: React.ReactNode;
}

export const Button: React.FC<ButtonProps> = ({
  children,
  variant = 'primary',
  size = 'md',
  isLoading = false,
  glow = false,
  leftIcon,
  rightIcon,
  className = '',
  disabled,
  ...props
}) => {
  const baseStyles = `
    relative inline-flex items-center justify-center
    font-semibold transition-all duration-200
    active:scale-95 disabled:opacity-50 disabled:cursor-not-allowed
    rounded-lg overflow-hidden group
    focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--focus-ring)] focus-visible:ring-offset-2 focus-visible:ring-offset-[var(--bg-primary)]
  `;

  const sizeStyles = {
    sm: 'px-3 py-1.5 text-xs',
    md: 'px-4 py-2 text-sm',
    lg: 'px-6 py-3 text-base',
  };

  const variantStyles = {
    primary: `
      bg-gradient-to-r from-[var(--accent-primary)] to-[var(--accent-secondary)]
      text-white dark:text-black
      shadow-[var(--shadow-sm)] hover:shadow-[var(--shadow-lg)]
      hover:brightness-105
    `,
    secondary: `
      bg-[var(--bg-card-alpha)] text-[var(--text-primary)]
      border border-[var(--border-color)]
      shadow-[var(--shadow-sm)]
      hover:bg-[var(--bg-card)] hover:border-[var(--accent-primary)] hover:shadow-[var(--shadow-md)]
      backdrop-blur-md
    `,
    ghost: `
      bg-transparent text-[var(--text-secondary)]
      hover:text-[var(--text-primary)] hover:bg-[var(--accent-soft)]
    `,
    danger: `
      bg-red-500/10 text-red-600 dark:text-red-400
      border border-red-500/25
      hover:bg-red-500/15
    `,
    outline: `
      bg-transparent text-[var(--text-primary)]
      border border-[var(--border-color)]
      hover:border-[var(--accent-primary)] hover:text-[var(--accent-primary)] hover:bg-[var(--accent-soft)]
    `,
  };

  const glowStyles = glow
    ? 'ring-1 ring-[var(--accent-soft)] shadow-[var(--shadow-lg)] hover:shadow-[var(--shadow-xl)]'
    : '';

  return (
    <button
      className={`
        ${baseStyles}
        ${sizeStyles[size]}
        ${variantStyles[variant]}
        ${glowStyles}
        ${className}
      `}
      disabled={isLoading || disabled}
      {...props}
    >
      {isLoading ? (
        <Loader2 className="w-4 h-4 mr-2 animate-spin" />
      ) : leftIcon ? (
        <span className="mr-2">{leftIcon}</span>
      ) : null}

      <span className="relative z-10 flex items-center gap-2">
        {children}
      </span>

      {rightIcon && !isLoading && <span className="ml-2">{rightIcon}</span>}

      {/* Shine effect on hover */}
      {variant !== 'ghost' && (
        <div className="absolute inset-0 -translate-x-full group-hover:animate-[shimmer_2s_infinite] bg-gradient-to-r from-transparent via-white/10 to-transparent z-0" />
      )}
    </button>
  );
};

export default Button;

// web-app/src/shared/ui/Button/Button.vue
<script setup lang="ts">
import { computed } from 'vue'

type ButtonVariant = 'primary' | 'secondary' | 'outline' | 'ghost' | 'danger' | 'success' | 'warning' | 'info'
type ButtonSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl'
type ButtonRadius = 'none' | 'sm' | 'md' | 'lg' | 'full'

interface Props {
  variant?: ButtonVariant
  size?: ButtonSize
  loading?: boolean
  disabled?: boolean
  type?: 'button' | 'submit' | 'reset'
  block?: boolean
  rounded?: ButtonRadius
  shadow?: boolean
  icon?: boolean
  ariaLabel?: string
}

const props = withDefaults(defineProps<Props>(), {
  variant: 'primary',
  size: 'md',
  type: 'button',
  block: false,
  rounded: 'lg',
  shadow: false,
  icon: false
})

const emit = defineEmits<{
  click: [event: MouseEvent]
}>()

const variantClasses = computed(() => {
  const variants: Record<ButtonVariant, string> = {
    primary: 'bg-primary-500 text-white hover:bg-primary-600 focus:ring-primary-500 active:bg-primary-700',
    secondary: 'bg-bg-tertiary text-text-primary hover:bg-border focus:ring-primary-500',
    outline: 'bg-transparent border-2 border-primary-500 text-primary-600 hover:bg-primary-50 focus:ring-primary-500',
    ghost: 'bg-transparent text-text-secondary hover:bg-bg-tertiary hover:text-text-primary focus:ring-primary-500',
    danger: 'bg-error text-white hover:bg-error/90 focus:ring-error active:bg-error/80',
    success: 'bg-success text-white hover:bg-success/90 focus:ring-success active:bg-success/80',
    warning: 'bg-warning text-white hover:bg-warning/90 focus:ring-warning active:bg-warning/80',
    info: 'bg-info text-white hover:bg-info/90 focus:ring-info active:bg-info/80'
  }
  return variants[props.variant]
})

const sizeClasses = computed(() => {
  const sizes: Record<ButtonSize, string> = {
    xs: 'px-2.5 py-1.5 text-xs',
    sm: 'px-3 py-2 text-sm',
    md: 'px-4 py-2 text-sm',
    lg: 'px-5 py-2.5 text-base',
    xl: 'px-6 py-3 text-base'
  }
  return sizes[props.size]
})

const radiusClasses = computed(() => {
  const radii: Record<ButtonRadius, string> = {
    none: 'rounded-none',
    sm: 'rounded',
    md: 'rounded-md',
    lg: 'rounded-lg',
    full: 'rounded-full'
  }
  return radii[props.rounded]
})

const baseClasses = computed(() => [
  'inline-flex items-center justify-center gap-2 font-medium transition-all duration-200',
  'focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-bg-primary',
  'disabled:opacity-50 disabled:cursor-not-allowed disabled:pointer-events-none',
  'active:scale-[0.98]',
  variantClasses.value,
  sizeClasses.value,
  radiusClasses.value,
  props.shadow ? 'shadow-md hover:shadow-lg' : '',
  props.block ? 'w-full' : '',
  props.icon ? '!p-2' : ''
])

function handleClick(event: MouseEvent) {
  if (!props.loading && !props.disabled) {
    emit('click', event)
  }
}
</script>

<template>
  <button
    :type="type"
    :class="baseClasses"
    :disabled="disabled || loading"
    :aria-label="ariaLabel"
    :aria-busy="loading"
    @click="handleClick"
  >
    <span
      v-if="loading"
      class="inline-block border-2 border-current border-t-transparent rounded-full animate-spin"
      :class="{
        'w-3 h-3': size === 'xs' || size === 'sm',
        'w-4 h-4': size === 'md',
        'w-5 h-5': size === 'lg' || size === 'xl'
      }"
      aria-hidden="true"
    />
    <slot />
  </button>
</template>
