// new/components/Button.tsx
import React from 'react';
import { Loader2 } from 'lucide-react';

interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: 'primary' | 'secondary' | 'ghost' | 'danger';
  isLoading?: boolean;
  glow?: boolean;
}

export const Button: React.FC<ButtonProps> = ({ 
  children, 
  variant = 'primary', 
  isLoading = false, 
  glow = false,
  className = '',
  ...props 
}) => {
  const baseStyles = "relative inline-flex items-center justify-center px-6 py-3 text-sm font-semibold transition-all duration-200 active:scale-95 disabled:opacity-50 disabled:cursor-not-allowed rounded-lg overflow-hidden group";
  
  const variants = {
    primary: "bg-white text-black hover:bg-gray-100 border border-transparent",
    secondary: "bg-white/5 text-white border border-white/10 hover:bg-white/10 hover:border-white/20 backdrop-blur-md",
    ghost: "bg-transparent text-gray-400 hover:text-white hover:bg-white/5",
    danger: "bg-red-500/10 text-red-500 border border-red-500/20 hover:bg-red-500/20",
  };

  const glowStyles = glow ? "shadow-[0_0_20px_rgba(0,240,255,0.3)] hover:shadow-[0_0_30px_rgba(0,240,255,0.5)] border-cyan-500/30" : "";

  // Special Cyberpunk override for primary with glow
  const finalVariantClass = (variant === 'primary' && glow) 
    ? "bg-gradient-to-r from-cyan-500 to-blue-600 text-white border-none" 
    : variants[variant];

  return (
    <button 
      className={`${baseStyles} ${finalVariantClass} ${glowStyles} ${className}`}
      disabled={isLoading || props.disabled}
      {...props}
    >
      {isLoading ? (
        <Loader2 className="w-4 h-4 mr-2 animate-spin" />
      ) : null}
      
      <span className="relative z-10 flex items-center gap-2">
        {children}
      </span>
      
      {/* Shine effect on hover */}
      {variant !== 'ghost' && (
        <div className="absolute inset-0 -translate-x-full group-hover:animate-[shimmer_2s_infinite] bg-gradient-to-r from-transparent via-white/10 to-transparent z-0" />
      )}
    </button>
  );
};

// web-app/src/shared/ui/Button/Button.vue
<script setup lang="ts">
import { computed } from 'vue'

type ButtonVariant = 'primary' | 'secondary' | 'outline' | 'ghost' | 'danger' | 'success' | 'warning' | 'info'
type ButtonSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl'
type ButtonRadius = 'none' | 'sm' | 'md' | 'lg' | 'full'

interface Props {
  variant?: ButtonVariant
  size?: ButtonSize
  loading?: boolean
  disabled?: boolean
  type?: 'button' | 'submit' | 'reset'
  block?: boolean
  rounded?: ButtonRadius
  shadow?: boolean
  icon?: boolean
  ariaLabel?: string
}

const props = withDefaults(defineProps<Props>(), {
  variant: 'primary',
  size: 'md',
  type: 'button',
  block: false,
  rounded: 'lg',
  shadow: false,
  icon: false
})

const emit = defineEmits<{
  click: [event: MouseEvent]
}>()

const variantClasses = computed(() => {
  const variants: Record<ButtonVariant, string> = {
    primary: 'bg-primary-500 text-white hover:bg-primary-600 focus:ring-primary-500 active:bg-primary-700',
    secondary: 'bg-bg-tertiary text-text-primary hover:bg-border focus:ring-primary-500',
    outline: 'bg-transparent border-2 border-primary-500 text-primary-600 hover:bg-primary-50 focus:ring-primary-500',
    ghost: 'bg-transparent text-text-secondary hover:bg-bg-tertiary hover:text-text-primary focus:ring-primary-500',
    danger: 'bg-error text-white hover:bg-error/90 focus:ring-error active:bg-error/80',
    success: 'bg-success text-white hover:bg-success/90 focus:ring-success active:bg-success/80',
    warning: 'bg-warning text-white hover:bg-warning/90 focus:ring-warning active:bg-warning/80',
    info: 'bg-info text-white hover:bg-info/90 focus:ring-info active:bg-info/80'
  }
  return variants[props.variant]
})

const sizeClasses = computed(() => {
  const sizes: Record<ButtonSize, string> = {
    xs: 'px-2.5 py-1.5 text-xs',
    sm: 'px-3 py-2 text-sm',
    md: 'px-4 py-2 text-sm',
    lg: 'px-5 py-2.5 text-base',
    xl: 'px-6 py-3 text-base'
  }
  return sizes[props.size]
})

const radiusClasses = computed(() => {
  const radii: Record<ButtonRadius, string> = {
    none: 'rounded-none',
    sm: 'rounded',
    md: 'rounded-md',
    lg: 'rounded-lg',
    full: 'rounded-full'
  }
  return radii[props.rounded]
})

const baseClasses = computed(() => [
  'inline-flex items-center justify-center gap-2 font-medium transition-all duration-200',
  'focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-bg-primary',
  'disabled:opacity-50 disabled:cursor-not-allowed disabled:pointer-events-none',
  'active:scale-[0.98]',
  variantClasses.value,
  sizeClasses.value,
  radiusClasses.value,
  props.shadow ? 'shadow-md hover:shadow-lg' : '',
  props.block ? 'w-full' : '',
  props.icon ? '!p-2' : ''
])

function handleClick(event: MouseEvent) {
  if (!props.loading && !props.disabled) {
    emit('click', event)
  }
}
</script>

<template>
  <button
    :type="type"
    :class="baseClasses"
    :disabled="disabled || loading"
    :aria-label="ariaLabel"
    :aria-busy="loading"
    @click="handleClick"
  >
    <span
      v-if="loading"
      class="inline-block border-2 border-current border-t-transparent rounded-full animate-spin"
      :class="{
        'w-3 h-3': size === 'xs' || size === 'sm',
        'w-4 h-4': size === 'md',
        'w-5 h-5': size === 'lg' || size === 'xl'
      }"
      aria-hidden="true"
    />
    <slot />
  </button>
</template>
